apiVersion: v1
kind: ConfigMap
metadata: 
  name: aws-auth
  namespace: kube-system
data: 
  mapRoles: |
    - rolearn: arn:aws:iam::015699013905:role/EKS-Worker-NodeInstanceRole-LUGMFL7QCVB0
      username: system:node:{{EC2PrivateDNSName}}
      groups: 
        - system:bootstrappers
        - system:nodes